[target.aarch64-linux-android]
rustflags = ["-C", "link-args=-Wl,-soname,libhct.so"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-args=-Wl,-soname,libhct.so"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-args=-Wl,-soname,libhct.so"]

[target.i686-linux-android]
rustflags = ["-C", "link-args=-Wl,-soname,libhct.so"]
